### ISSUE TITLE
NoSuchMethodError with bouncycastle 1.64

### ISSUE THREAD

**Issue by ties** [RIPE-NCC/rpki-commons#19]
<img width="1384" alt="Screenshot 2020-04-24 at 11 50 31" src="https://user-images.githubusercontent.com/199058/80205497-0000f580-862b-11ea-87f8-5b9bb3514cc7.png">

NoSuchMethodError for missing method. This needs investigation.

**Comment by erikrozendaal** [comment]
This may occur again with https://github.com/RIPE-NCC/rpki-commons/pull/23, but it looks like a class file was not recompiled correctly.

**Comment by ties** [comment]
This stacktrace was from core (see 065a070aead2e4ac7539ec93a9a22dcc62a9fe23 and the commits surrounding it).

**Comment by ties** [comment]
Was caused by another copy of bouncy castle on the classpath which was loaded earlier.
